In [5]:
import numpy as np
import pandas as pd

In [2]:
obj = pd.Series([[4, 5], [5, 6]])

In [3]:
obj

0    [4, 5]
1    [5, 6]
dtype: object

In [4]:
obj.values

array([list([4, 5]), list([5, 6])], dtype=object)

In [5]:
obj.index

RangeIndex(start=0, stop=2, step=1)

In [4]:
obj = pd.Series([4, 7, -5, 3])

In [5]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [6]:
obj.values

array([ 4,  7, -5,  3])

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [9]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [11]:
obj2['a']

-5

In [12]:
obj2['d'] = 6

In [14]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [15]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [16]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [18]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [19]:
'b' in obj2

True

In [20]:
'e' in obj2

False

In [21]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon':16000, 'Utah': 5000}

In [22]:
obj3 = pd.Series(sdata)

In [23]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [24]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [25]:
obj4 = pd.Series(sdata, index=states)

In [26]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [27]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [28]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [29]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [30]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [31]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [32]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [33]:
obj4.name = 'population'

In [34]:
obj4.index.name = 'state'

In [35]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [36]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [37]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [38]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [45]:
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 2002, 2001, 2002, 2003],
    'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}

In [46]:
frame = pd.DataFrame(data)

In [47]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [48]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [49]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [101]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index=['one', 'two', 'three', 'four', 'five', 'six'])

In [102]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [52]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [54]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [55]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [56]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [57]:
frame2['debt'] = 16.5

In [58]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [59]:
frame2['debt'] = np.arange(6.)

In [60]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [61]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [62]:
frame2['pop'] = val

In [63]:
frame2

year   state  pop  debt
one    2000    Ohio  NaN   0.0
two    2001    Ohio -1.2   1.0
three  2002    Ohio  NaN   2.0
four   2001  Nevada -1.5   3.0
five   2002  Nevada -1.7   4.0
six    2003  Nevada  NaN   5.0

In [64]:
frame2['eastern'] = frame2.state == 'Ohio'

In [65]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  NaN   0.0     True
two    2001    Ohio -1.2   1.0     True
three  2002    Ohio  NaN   2.0     True
four   2001  Nevada -1.5   3.0    False
five   2002  Nevada -1.7   4.0    False
six    2003  Nevada  NaN   5.0    False

In [66]:
del frame2['eastern']

In [67]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [84]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
      'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [85]:
frame3 = pd.DataFrame(pop)

In [86]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [87]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [108]:
pd.DataFrame(pop, columns=['Ohio', 'Nevada'], index=[2001, 2002, 2003])

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [110]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}

In [111]:
pdata

{'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64, 'Nevada': 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64}

In [112]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [113]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [114]:
frame3.index.name = 'year'

In [115]:
frame3.columns.name = 'state'

In [116]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [117]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [118]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [123]:
x = np.array([(1,2.,'Hello'), (2,3.,"World")], dtype=[('foo', 'i4'),('bar', 'f4'), ('baz', 'S10')])

In [126]:
x['foo']

array([1, 2], dtype=int32)

In [125]:
pd.DataFrame(x)

foo  bar       baz
0    1  2.0  b'Hello'
1    2  3.0  b'World'

In [127]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [128]:
index = obj.index

In [129]:
index

Index(['a', 'b', 'c'], dtype='object')

In [130]:
index[1:]

Index(['b', 'c'], dtype='object')

In [131]:
arr = obj.values

In [132]:
arr

array([0, 1, 2])

In [133]:
arr[0] = 3

In [134]:
obj

a    3
b    1
c    2
dtype: int64

In [136]:
labels = pd.Index(np.arange(3))

In [137]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [138]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [139]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [140]:
obj2.index is labels

True

In [141]:
obj2.index == labels

array([ True,  True,  True])

In [149]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [150]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [151]:
'Ohio' in frame3.columns

True

In [152]:
2003 in frame3.index

False

In [153]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [154]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [159]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [160]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [197]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [198]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [218]:
obj3.reindex(range(0, 10, 2), method='ffill', tolerance=2)

0      blue
2    purple
4    yellow
6    yellow
8       NaN
dtype: object

In [166]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                    index=['a', 'c', 'b'],
                    columns=['Ohio', 'Texas', 'California'])

In [167]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
b     6      7           8

In [170]:
frame2 = frame.reindex(['a', 'b', 'c'])

In [171]:
frame2

Ohio  Texas  California
a     0      1           2
b     6      7           8
c     3      4           5

In [172]:
states = ['Texas', 'California', 'Utah']

In [173]:
frame.reindex(columns=states)

Texas  California  Utah
a      1           2   NaN
c      4           5   NaN
b      7           8   NaN

In [174]:
frame.loc['a']

Ohio          0
Texas         1
California    2
Name: a, dtype: int64

In [175]:
frame['California']

a    2
c    5
b    8
Name: California, dtype: int64

In [179]:
frame.loc[['a', 'b']]['Ohio']

a    0
b    6
Name: Ohio, dtype: int64

In [2]:
obj = pd.Series(np.arange(5.0), index=['a', 'b', 'c', 'd', 'e'])

In [3]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [4]:
new_obj = obj.drop('c')

In [5]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [6]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [8]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [9]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [10]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [11]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [12]:
obj.drop('c', inplace=True)

In [13]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [22]:
obj = pd.Series(np.arange(4.), index=['a', 'c', 'b', 'd'])

In [23]:
obj

a    0.0
c    1.0
b    2.0
d    3.0
dtype: float64

In [24]:
obj['b']

2.0

In [25]:
obj[1]

1.0

In [26]:
obj[2:4]

b    2.0
d    3.0
dtype: float64

In [27]:
obj['a':'b']

a    0.0
c    1.0
b    2.0
dtype: float64

In [28]:
obj[['b', 'a' ,'d']]

b    2.0
a    0.0
d    3.0
dtype: float64

In [29]:
obj[[1, 3]]

c    1.0
d    3.0
dtype: float64

In [30]:
obj[obj<2]

a    0.0
c    1.0
dtype: float64

In [31]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [32]:
data.loc[['Ohio', 'Colorado'], ['one', 'two']]

one  two
Ohio        0    1
Colorado    4    5

In [37]:
obj['a':'b'] = 4

In [38]:
obj

a    4.0
c    4.0
b    4.0
d    5.0
dtype: float64

In [39]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [40]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [41]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [42]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [48]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [49]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [52]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [53]:
data[data < 5]

one  two  three  four
Ohio      0.0  1.0    2.0   3.0
Colorado  4.0  NaN    NaN   NaN
Utah      NaN  NaN    NaN   NaN
New York  NaN  NaN    NaN   NaN

In [54]:
data[data < 5] = 0

In [55]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [56]:
arr2d = np.arange(16).reshape((4, 4))

In [57]:
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
arr2d < 5

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [59]:
arr2d[arr2d < 5]

array([0, 1, 2, 3, 4])

In [60]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [61]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [62]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [66]:
arr2d[1 : 3, [1, 3]]

array([[ 5,  7],
       [ 9, 11]])

In [67]:
arr2d[[1, 3], [1, 3]]

array([ 5, 15])

In [68]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [69]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [74]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [78]:
data[['one', 'two']]

one  two
Ohio        0    0
Colorado    0    5
Utah        8    9
New York   12   13

In [79]:
ser = pd.Series(np.arange(3.))

In [80]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [82]:
ser[1]

1.0

In [83]:
ser[:1]

0    0.0
dtype: float64

In [84]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [85]:
ser.iloc[:1]

0    0.0
dtype: float64

In [86]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [88]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [89]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [90]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [92]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                  index=['Ohio', 'Texas', 'Colorado'])

In [93]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [95]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [96]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [97]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [98]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

In [99]:
df1

A
0  1
1  2

In [100]:
df2

B
0  3
1  4

In [101]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [102]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                  columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                  columns=list('abcde'))

In [108]:
df2.at[0, 'e'] = np.nan

In [109]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [110]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   NaN
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [111]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [113]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   NaN
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [115]:
df2.add(df1, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   NaN
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [117]:
1 / df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [118]:
df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [119]:
df1.reindex(columns=df2.columns)

a    b     c     d   e
0  0.0  1.0   2.0   3.0 NaN
1  4.0  5.0   6.0   7.0 NaN
2  8.0  9.0  10.0  11.0 NaN

In [120]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [121]:
np.arange(3) + np.arange(9).reshape((3, 3))

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [122]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [123]:
arr[0]

array([0., 1., 2., 3.])

In [124]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [126]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                    columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [143]:
series = frame.iloc[0]

In [144]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    1.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [145]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [146]:
series[1] = 2

In [147]:
frame

b     d     e
Utah    0.0   2.0   2.0
Ohio    1.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [148]:
series[1] = 1

In [149]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    1.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [150]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    1.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [151]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [152]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    1.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [153]:
series3 = frame['d']

In [154]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    1.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [155]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [156]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -3.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [2]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [3]:
frame

b         d         e
Utah    0.206819 -0.873139  0.339844
Ohio   -1.853531  0.176623  0.005488
Texas  -1.474438 -1.794259  0.417630
Oregon  0.969920  0.994175 -1.086704

In [4]:
np.abs(frame)

b         d         e
Utah    0.206819  0.873139  0.339844
Ohio    1.853531  0.176623  0.005488
Texas   1.474438  1.794259  0.417630
Oregon  0.969920  0.994175  1.086704

In [7]:
frame.max(axis='columns')7744

Utah      0.339844
Ohio      0.176623
Texas     0.417630
Oregon    0.994175
dtype: float64

In [17]:
f = lambda x : x.max() - x.min()

In [18]:
frame.apply(f)

b    2.823451
d    2.788434
e    1.504333
dtype: float64

In [19]:
frame.apply(f, axis='columns')

Utah      1.212984
Ohio      2.030155
Texas     2.211889
Oregon    2.080878
dtype: float64

In [22]:
f = lambda x : pd.Series([x.min(), x.max()], index=['min', 'max'])

In [23]:
frame.apply(f)

b         d         e
min -1.853531 -1.794259 -1.086704
max  0.969920  0.994175  0.417630

In [28]:
format = lambda x : '%.2f' % x

In [29]:
frame.applymap(format)

b      d      e
Utah     0.21  -0.87   0.34
Ohio    -1.85   0.18   0.01
Texas   -1.47  -1.79   0.42
Oregon   0.97   0.99  -1.09

In [30]:
frame['e'].map(format)

Utah       0.34
Ohio       0.01
Texas      0.42
Oregon    -1.09
Name: e, dtype: object

In [31]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [32]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [33]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                    index=['three', 'one'],
                    columns=['d', 'a', 'b', 'c'])

In [34]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [35]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [36]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [37]:
obj = pd.Series([4, 7, -3, 2])

In [38]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [39]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [40]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [41]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [42]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [43]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [44]:
frame.sort_values(by=1, axis=1)

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [49]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [50]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [51]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [59]:
obj.rank(ascending=False, method='min')

0    1.0
1    7.0
2    1.0
3    3.0
4    5.0
5    6.0
6    3.0
dtype: float64

In [54]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                     'c': [-2, 5, 8, -2.5]})

In [55]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [56]:
frame.rank()

b    a    c
0  3.0  1.5  2.0
1  4.0  3.5  3.0
2  1.0  1.5  4.0
3  2.0  3.5  1.0

In [57]:
frame.rank(axis=1)

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [60]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [62]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [63]:
obj.index.is_unique

False

In [64]:
obj['a']

a    0
a    1
dtype: int64

In [65]:
obj['c']

4

In [66]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [67]:
df

0         1         2
a -0.868946  1.204880 -1.180281
a -1.162636  1.599119  0.585101
b -0.655039 -0.168336  0.548517
b  1.640352  0.704115  2.113180

In [68]:
df.loc['b']

0         1         2
b -0.655039 -0.168336  0.548517
b  1.640352  0.704115  2.113180

In [69]:
np.max(np.arange(9).reshape((3, 3)))

8

In [71]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                 index=['a', 'b', 'c', 'd'],
                 columns=['one', 'two'])

In [72]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [73]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [74]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [75]:
df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [76]:
df.idxmax()

one    b
two    d
dtype: object

In [88]:
df['one'].argmax()

/home/trierbo/miniconda2/envs/pydata/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: 'argmax' is deprecated, use 'idxmax' instead. The behavior of 'argmax'
will be corrected to return the positional maximum in the future.
Use 'series.values.argmax' to get the position of the maximum now.
  """Entry point for launching an IPython kernel.


'b'

In [77]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [78]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [83]:
obj = pd.Series(['a', 'b', 'b', 'c'] * 4)

In [84]:
obj

0     a
1     b
2     b
3     c
4     a
5     b
6     b
7     c
8     a
9     b
10    b
11    c
12    a
13    b
14    b
15    c
dtype: object

In [85]:
obj.describe()

count     16
unique     3
top        b
freq       8
dtype: object

In [1]:
import pandas_datareader.data as web
import fix_yahoo_finance as fyf

fyf.pdr_override()

In [2]:
all_data = {ticker: web.get_data_yahoo(ticker)
           for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded


In [6]:
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [7]:
price.tail()

AAPL         IBM        MSFT         GOOG
Date                                                       
2018-09-04  228.360001  145.679993  111.709999  1197.000000
2018-09-05  226.869995  146.660004  108.489998  1186.479980
2018-09-06  223.100006  146.389999  108.739998  1171.439941
2018-09-07  221.300003  145.449997  108.209999  1164.829956
2018-09-10  218.330002  145.649994  109.379997  1164.640015

In [8]:
volume.tail()

AAPL      IBM        MSFT       GOOG
Date                                                  
2018-09-04  27390100.0  3326200  22634600.0  1831000.0
2018-09-05  33333000.0  3126500  32872400.0  2061300.0
2018-09-06  34290000.0  4248800  23477600.0  1888500.0
2018-09-07  37619800.0  4693100  22498600.0  1401300.0
2018-09-10  39262400.0  3339400  20711600.0  1115400.0

In [9]:
returns = price.pct_change()

In [10]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2018-09-04  0.003207 -0.005462 -0.005519 -0.017395
2018-09-05 -0.006525  0.006727 -0.028825 -0.008789
2018-09-06 -0.016617 -0.001841  0.002304 -0.012676
2018-09-07 -0.008068 -0.006421 -0.004874 -0.005643
2018-09-10 -0.013421  0.001375  0.010812 -0.000163

- 样本协方差
$cov(x,y) = \frac{1}{n}\sum_i^n{(x_i-\overline{x})(y_i-\overline{y})}$
- 相关系数
$corr(x,y) = \frac{cov(x,y)}{\sqrt{var(x)var(y)}}$

In [11]:
returns['MSFT'].corr(returns['IBM'])

0.43547758409625253

In [12]:
returns['MSFT'].cov(returns['IBM'])

0.0001618156055985148

In [13]:
returns.columns

Index(['AAPL', 'IBM', 'MSFT', 'GOOG'], dtype='object')

In [14]:
returns.index

DatetimeIndex(['1962-01-02', '1962-01-03', '1962-01-04', '1962-01-05',
               '1962-01-08', '1962-01-09', '1962-01-10', '1962-01-11',
               '1962-01-12', '1962-01-15',
               ...
               '2018-08-27', '2018-08-28', '2018-08-29', '2018-08-30',
               '2018-08-31', '2018-09-04', '2018-09-05', '2018-09-06',
               '2018-09-07', '2018-09-10'],
              dtype='datetime64[ns]', name='Date', length=14271, freq=None)

In [18]:
returns.index.name = 'Date'

In [19]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2018-09-04  0.003207 -0.005462 -0.005519 -0.017395
2018-09-05 -0.006525  0.006727 -0.028825 -0.008789
2018-09-06 -0.016617 -0.001841  0.002304 -0.012676
2018-09-07 -0.008068 -0.006421 -0.004874 -0.005643
2018-09-10 -0.013421  0.001375  0.010812 -0.000163

In [20]:
returns.name = 'stock'

In [21]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2018-09-04  0.003207 -0.005462 -0.005519 -0.017395
2018-09-05 -0.006525  0.006727 -0.028825 -0.008789
2018-09-06 -0.016617 -0.001841  0.002304 -0.012676
2018-09-07 -0.008068 -0.006421 -0.004874 -0.005643
2018-09-10 -0.013421  0.001375  0.010812 -0.000163

In [22]:
returns.MSFT.corr(returns.IBM)

0.43547758409625253

In [23]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.357045  0.387484  0.453773
IBM   0.357045  1.000000  0.435478  0.389957
MSFT  0.387484  0.435478  1.000000  0.466544
GOOG  0.453773  0.389957  0.466544  1.000000

In [24]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000860  0.000176  0.000239  0.000180
IBM   0.000176  0.000251  0.000162  0.000098
MSFT  0.000239  0.000162  0.000463  0.000145
GOOG  0.000180  0.000098  0.000145  0.000364

In [32]:
returns.corrwith(returns.iloc[:, 1:3])

AAPL    NaN
GOOG    NaN
IBM     1.0
MSFT    1.0
dtype: float64

In [26]:
returns.corrwith(volume)

AAPL   -0.002324
IBM    -0.000472
MSFT   -0.004140
GOOG    0.047383
dtype: float64

In [27]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [28]:
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

In [33]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [34]:
obj.value_counts(sort=False)

c    3
a    3
b    2
d    1
dtype: int64

In [35]:
pd.value_counts(obj.values, sort=False)

c    3
a    3
b    2
d    1
dtype: int64

In [36]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [37]:
mask = obj.isin(['b', 'c'])

In [38]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [39]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [40]:
df1 = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df2 = pd.DataFrame([[1, 20, 3], [4, 50, 6], [7, 80, 9]])

In [41]:
df1.isin(df2)

0      1     2
0  True  False  True
1  True  False  True
2  True  False  True

In [44]:
df1 = pd.DataFrame(np.arange(16).reshape((4, 4)))
df2 = pd.DataFrame(np.arange(25).reshape((5, 5)))

In [47]:
mask = df2.isin(df1)

In [48]:
df2[mask]

0    1    2    3   4
0  0.0  1.0  2.0  3.0 NaN
1  NaN  NaN  NaN  NaN NaN
2  NaN  NaN  NaN  NaN NaN
3  NaN  NaN  NaN  NaN NaN
4  NaN  NaN  NaN  NaN NaN

In [49]:
df2.isin?

In [50]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])

In [51]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

In [58]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                    'Qu2': [2, 3, 1, 2, 3],
                    'Qu3': [1, 6, 2, 4, 4]})

In [59]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    6
2    4    1    2
3    3    2    4
4    4    3    4

In [60]:
result = data.apply(pd.value_counts).fillna(0)

In [61]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
6  0.0  0.0  1.0